In [1]:
# Multiplication of Tensors

import torch
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
print(x * 10)

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])


In [2]:
# Addition of Tensors

x = torch.tensor([[1,2,3,4], [5,6,7,8]])
y = x.add(10)
print(y)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])


In [6]:
# Reshaping the Tensor

y = torch.tensor([2, 3, 1, 0])

y = y.view(4,1)

In [8]:
# Another way to reshape a tensor is by using the squeeze method, where the axis index that we want to remove is provided. Note that this is applicable only when the axis we want to remove has only one item in that
# dimension:

x = torch.randn(10,1,10)
z1 = torch.squeeze(x, 1) # similar to np.squeeze()

# The same operation can be directly performed on
# x by calling squeeze and the dimension to squeeze out
z2 = x.squeeze(1)
assert torch.all(z1 == z2)
# all the elements in both tensors are equal
print('Squeeze:\n', x.shape, z1.shape)

Squeeze:
 torch.Size([10, 1, 10]) torch.Size([10, 10])


In [9]:
# The opposite of squeeze is unsqueeze, which means we add a dimension to the matrix:

x = torch.randn(10,10)
print(x.shape)

z1 = x.unsqueeze(0)
print(z1.shape)

torch.Size([10, 10])
torch.Size([1, 10, 10])


In [10]:
# The same can be achieved using [None] indexing adding None will auto create a fake dim at the specified axis

x = torch.randn(10,10)
z2, z3, z4 = x[None], x[:,None], x[:,:,None]
print(z2.shape, z3.shape, z4.shape)


torch.Size([1, 10, 10]) torch.Size([10, 1, 10]) torch.Size([10, 10, 1])


In [11]:
# Matrix Multiplication of two different tensors

x = torch.tensor([[1,2,3,4], [5,6,7,8]])
print(torch.matmul(x, y))

# Matrix Multiplication can also be done using 

# print(x@y)

tensor([[11],
        [35]])


In [12]:
# Concatenation of Tensors

import torch
x = torch.randn(10,10,10)
z = torch.cat([x,x], axis=0) # np.concatenate()
print('Cat axis 0:', x.shape, z.shape)

z = torch.cat([x,x], axis=1) # np.concatenate()
print('Cat axis 1:', x.shape, z.shape)

Cat axis 0: torch.Size([10, 10, 10]) torch.Size([20, 10, 10])
Cat axis 1: torch.Size([10, 10, 10]) torch.Size([10, 20, 10])


In [13]:
# ExTracting maximum values from a tensor

x = torch.arange(25).reshape(5,5)
print('Max:', x.shape, x.max())

Max: torch.Size([5, 5]) tensor(24)


In [14]:
# Extracting max value from the Row index where maximum value is present

x.max(dim=0)

torch.return_types.max(
values=tensor([20, 21, 22, 23, 24]),
indices=tensor([4, 4, 4, 4, 4]))

In [15]:
# Fetching Maximum values across the column

m, argm = x.max(dim=1)
print('Max in axis 1:\n', m, argm)

Max in axis 1:
 tensor([ 4,  9, 14, 19, 24]) tensor([4, 4, 4, 4, 4])


In [16]:
# Permute the dimensions of a tensor object:

x = torch.randn(10,20,30)
z = x.permute(2,0,1) # np.permute()
print('Permute dimensions:', x.shape, z.shape)


Permute dimensions: torch.Size([10, 20, 30]) torch.Size([30, 10, 20])


**NOTE**: The shape of the tensor changes when we perform permute on top of the
original tensor.

Never reshape (that is, use tensor.view on) a tensor to swap the
dimensions. Even though Torch will not throw an error, this is
wrong and will create unforeseen results during training. If you
need to swap dimensions, always use permute

Standard mathematical operations, such as abs, add, argsort,
ceil, floor, sin, cos, tan, cumsum, cumprod, diag, eig, exp, log, log2, log10,
mean, median, mode, resize, round, sigmoid, softmax, square, sqrt, svd,
and transpose, to name a few, can be directly called on any tensor with or without
axes where applicable. You can always run dir(torch.Tensor) to see all the
methods possible for a Torch tensor and help(torch.Tensor.<method>) to go
through the official help and documentation for that method.
