In [1]:
# Import PyTorch and initialize a tensor by calling torch.tensor on a list:
import torch
x = torch.tensor([[1,2]])
y = torch.tensor([[1],[2]])


In [2]:
# Next, access the tensor object's shape and data type:

print(x.shape)
# torch.Size([1,2]) # one entity of two items
print(y.shape)
# torch.Size([2,1]) # two entities of one item each
print(x.dtype)
# torch.int64

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [3]:
# The data type of all elements within a tensor is the same. That means if a tensor contains data of different data types (such as a Boolean, an integer,
# and a float), the entire tensor is coerced to the most generic data type:

x = torch.tensor([False, 1, 2.0])
print(x)


tensor([0., 1., 2.])


In [6]:
# Generate a tensor object that has three rows and four columns filled with zeros:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:

# Generate a tensor object that has three rows and four columns filled with ones:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
# Generate three rows and four columns of values between 0 and 10 (including the low value but not including the high value):

torch.randint(low=0, high=10, size=(3,4))

tensor([[6, 9, 7, 8],
        [5, 8, 4, 7],
        [1, 4, 6, 0]])

In [9]:
# Generate random numbers between 0 and 1 with three rows and four columns:

torch.rand(3, 4)


tensor([[0.6841, 0.5517, 0.4143, 0.0024],
        [0.1594, 0.0657, 0.6866, 0.1957],
        [0.8139, 0.2308, 0.4323, 0.8827]])

In [11]:
# Finally, we can directly convert a NumPy array into a Torch tensor using torch.tensor(<numpy-array>):

import numpy as np

x = np.array([[10,20,30],[2,3,4]])
y = torch.tensor(x)
print(type(x), type(y))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
